export default `
ul.index-main-menu
                         li
                             button(data-props='registerPage')
                         li
                             button(data-props='loginPage')
                         li
                             button(data-props='404')
                         li
                             button(data-props='500')
                         li
                             button(data-props='userSettings')
                         li
                             button(data-props='chat')
                         li
                             button(data-props='changePassword')
                         li
                             button(data-props='changeAvatar')
`;
